core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('store/', include('store.urls')),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


store/urls.py
from django.urls import path
from . import views

from .views import CreatProduct, ProductList, ProductDetail, CreateSale, SaleList, SaleDetail


urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('add-product/', CreatProduct.as_view(), name='add_product'),
    path('add-sale/', CreateSale.as_view(), name='add_sale'),
    path('all-products/', ProductList.as_view(), name='all_products'),
    path('all-sales/', SaleList.as_view(), name='all_sales'),
    path('product-detail/<pk>', ProductDetail.as_view(), name='product_detail'),
    path('sale-detail/<pk>', SaleDetail.as_view(), name='sale_detail'),
    path('delete-sale/<pk>', views.DeleteSale.as_view(), name='delete_sale'),
    path('delete-product/<pk>', views.DeleteProduct.as_view(), name='delete_product'),
    path('update-product/<pk>', views.UpdateProduct.as_view(), name="update_product"),
    path('update-sale/<pk>', views.UpdateSale.as_view(), name='update_sale'),
    path('search/', views.search_func, name='search_func'),
]

store/models.py
from django.db import models

from django.utils import timezone
import datetime
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    category = models.ManyToManyField('Category', related_name='category')
    price = models.DecimalField(decimal_places=2, max_digits=90000,null=True)
    quantity = models.IntegerField(null=True)
    manufacturing_date = models.DateTimeField(null=True)
    expiry_date = models.DateTimeField(null=True)
    status = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
        
        
    def __str__(self):
        return f"{self.name}"
        
class Category(models.Model):
    name = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
    
    
    
class Sale(models.Model):
    customer_name = models.CharField(max_length=2000, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(null=True)
    phone = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)
    issued_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_issued = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.product

store/forms.py
from django import forms
from django.forms import ModelForm

from .models import Product, Sale


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ['created_by']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Product Name...'}),
            'description':forms.Textarea(attrs={'class':'form-control', 'cols':'2', 'rows':'2', 'placeholder':'Product Description...'}),
            'price':forms.TextInput(attrs={'class':'form-control','type':'number', 'placeholder':'Product Price...'}),
            'quantity':forms.TextInput(attrs={'class':'form-control','type':'number', 'placeholder':'Product Quantity...'}),
            'category':forms.SelectMultiple(attrs={'class':'form-control'}),
            'status':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Product Status...'}),
            'manufacturing_date':forms.TextInput(attrs={'class':'form-control','type':'date'}),
            'expiry_date':forms.TextInput(attrs={'class':'form-control','type':'date'}),
        }
        
class SaleForm(ModelForm):
    class Meta:
        model = Sale
        fields = "__all__"
        exclude = ['issued_by']
        widgets = {
            'product':forms.Select(attrs={'class':'form-control'}),
            'quantity':forms.TextInput(attrs={'class':'form-control','type':'number', 'placeholder':'Product Quantity...'}),
        }

store/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import Product, Sale

from django.utils import timezone

# Search Function Imports
from django.db.models import Q

# Import Message Framework
from django.contrib import messages

# Forms imports
from .forms import ProductForm, SaleForm

from django.contrib.auth.decorators import login_required


# Generic Views Imports
from django.views.generic import TemplateView, UpdateView, DeleteView, DetailView, CreateView, FormView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

class Dashboard(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'store/dashboard.html'
    context_object_name = 'products'
    login_url = '/auth/login/'
    redirect_field_name = 'next'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'dashboard'
        context['products'] = Product.objects.all()
        context['sales'] = Sale.objects.all()
        return context
    
    



class CreatProduct(FormView):
    template_name = 'store/add_product.html'
    form_class = ProductForm
    success_url = '/store/all-products/'
    context_object_name = 'products'
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.save()
        return super().form_valid(form)
    
class CreateSale(LoginRequiredMixin,FormView):
    template_name = 'store/add_sale.html'
    form_class = SaleForm
    success_url = '/store/all-sales/'
    login_url = '/auth/login/'
    redirect_field_name = 'next'
    context_object_name = 'sales'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'add_sale'
        context['sales'] = Sale.objects.all()
        context['sales_count'] = context['sales'].count()
        return context
    
    def form_valid(self, form):
        form.save(commit=False)
        form.instance.issued_by = self.request.user
        form.save()
        return super().form_valid(form)
    

class ProductList(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'store/all_products.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'all_products'
        context['model'] = Product.objects.all()
        return context
    
class SaleList(ListView):
    model = Sale
    context_object_name = 'sales'
    template_name = 'store/all_sales.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'all_sales'
        return context

class ProductDetail(DetailView):
    model = Product
    template_name = 'store/view_product.html'
    context_object_name = 'product'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'product_detail'
        context['product_cat'] = context['product'].category.all()
        context['product_cat_count'] = context['product_cat'].count()
        return context



class SaleDetail(DetailView):
    model = Sale
    template_name = 'store/view_sale.html'
    context_object_name = 'sale'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = 'sale_detail'
        return context


class DeleteSale(DeleteView):
    model = Sale
    template_name = "store/delete.html"
    context_object_name = 'obj'
    success_url = '/store/all-sales/'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'delete_sale'
        return context

class DeleteProduct(DeleteView):
    model = Product
    template_name = 'store/delete.html'
    context_object_name = 'obj'
    success_url = '/store/all-products/'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = 'delete_product' 
        return context

class UpdateProduct(UpdateView):
    model = Product
    template_name = 'store/add_product.html'
    success_url = '/store/all-products/'
    form_class = ProductForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = 'update_product'
        context['created_by'] = Product.objects.all()
        return context
    
            
    

class UpdateSale(UpdateView):
    model = Sale
    template_name = 'store/add_sale.html'
    success_url = '/store/all-sales/'
    form_class = SaleForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = 'update_sale'
        return context
    


def search_func(request):
    query = request.GET.get('query') if request.GET.get('query') != None else ''
    
    sales = Sale.objects.filter(
        Q(product__name__icontains=query) |
        Q(address__icontains=query) |
        Q(issued_by__username__icontains=query)
    )
    products = Product.objects.filter(
        Q(name__icontains=query) |
        Q(created_by__username__icontains=query)
    )
    sales_count = sales.count()
    products_count = products.count()
    
    context = {
        'sales':sales,
        'products':products,
        'sales_count':sales_count,
        'products_count':products_count,
        'query':query,
    }
    return render(request, 'store/search.html', context)

templates/store/add_product.html
{% extends "base/base.html" %}
{% load widget_tweaks %}

{% block title %}Add Product{% endblock  %}


{% block content %}
{% include "base/main_nav.html" %}
{% include "base/side_nav.html" %}

<div class="sale-container">
  <div class="card">
      <div class="card-body">
        {% if page == 'update_product' %}
        <h5 class="card-title">Update Product</h5>
        {% else %}
        <h5 class="card-title">Add Product</h5>
        {% endif %}
  
        <!-- No Labels Form -->
        <form class="row g-3" method="POST">
          {% csrf_token %}
          <div class="col-md-6">
            {% render_field form.name type="text" class="form-control" placeholder="Product Name" %}
          </div>
          <div class="col-md-6">
            {% render_field form.description type="text" class="form-control" rows='1' cols='1' placeholder="Product Description" %}
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="id_category">{{form.category.label}}</label>
              {% render_field form.category  class="form-select" placeholder="Select Product"%}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-floating">
              {% render_field form.price type="text" class="form-control" placeholder="Product Price" %}
              <label for="floatingName">Price</label>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-floating">
              {% render_field form.quantity type="number" class="form-control" placeholder="Product Quantity"%}
              <label for="floatingName">Quantity</label>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-floating">
              {% render_field form.manufacturing_date type="date" class="form-control" placeholder="Product Manufacturing Date"%}
              <label for="floatingName">Manufacturing Date</label>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-floating">
              {% render_field form.expiry_date type="date" class="form-control" placeholder="Product Expiry Date"%}
              <label for="floatingName">Expiry Date</label>
            </div>
          </div>
          <div class="col-md-6">
            {% render_field form.status type="text" class="form-control" placeholder="Product Status" %}
          </div>
   
          <div class="col-md-6">
            <input type="text" class="form-control" placeholder="Issued By: {{request.user}}" disabled>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary w-100">Add</button>
          </div>
        </form><!-- End No Labels Form -->
      </div>
  </div>
</div>



{% endblock  %}

templates/store/add_sale.html
{% extends "base/base.html" %}
{% load widget_tweaks %}

{% block title %}Add Sale{% endblock  %}


{% block content %}

{% include "base/main_nav.html" %}
{% include "base/side_nav.html" %}

<div class="sale-container">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Make a Sale</h5>
    
          <!-- No Labels Form -->
          <form class="row g-3" method="POST">
            {% csrf_token %}
            <div class="col-md-12">
              <div class="form-floating">
                {% render_field form.customer_name type="text" class="form-control" placeholder="Customer Name" %}
                <label for="id_product">{{form.customer_name.label}}</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                {% render_field form.product type="text" class="form-select" placeholder="Select Product"%}
                <label for="id_product">Product Name</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                {% render_field form.quantity type="number" class="form-control" placeholder="Select Product"%}
                <label for="floatingName">Quantity</label>
              </div>
            </div>
            <div class="col-12">
              <div class="form-floating">
                {% render_field form.address type="text" rows='3' cols='3' class="form-control" placeholder="Address" %}
                <label for="floatingName">{{form.address.label}}</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                {% render_field form.phone type="text" class="form-control" placeholder="Phone" %}
                <label for="floatingName">{{form.phone.label}}</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-floating">
                <input type="text" class="form-control" placeholder="Issued By: {{request.user}}" disabled>
                <label for="floatingName">{{request.user}}</label>
              </div>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary w-100">Add</button>
            </div>
          </form><!-- End No Labels Form -->
    
        </div>
    </div>
</div>
                            

{% endblock  %}

templates/store/all_products.html
{% extends "base/base.html" %}

{% block title %}All Products{% endblock  %}

{% block content %}
{% include "base/main_nav.html" %}

{% include "base/side_nav.html" %}

{% include "base/base_table.html" %}

{% endblock  %}

templates/store/all_sales.html
{% extends "base/base.html" %}

{% block title %}All Sales{% endblock  %}

{% block content %}
{% include "base/main_nav.html" %}
{% include "base/side_nav.html" %}
{% include "base/base_table.html" %}

{% endblock  %}

templates/store/delete.html
{% extends "base/delete.html" %}

{% block cont %}

    {% if page == 'delete_product' %}

        <h4 class="card-title">Do you want to Delete "<code class="text-danger">{{obj.name}}</code>" </h4>

    {% elif page == 'delete_sale' %}

        <h4 class="card-title">Do you want to Delete "<code class="text-danger">{{obj.product}}</code>" </h4>

    {% endif %}

{% endblock  %}

templates/store/search.html
{% extends "base/base.html" %}


{% block title %}Search Result{% endblock  %}

{% block content %}
{% include "base/main_nav.html" %}
{% include "base/side_nav.html" %}


<div class="main" id="main">
    <div class="search-mt container">
        <div class="row">
            <p>{{sales_count}} sale{{sales_count|pluralize}} available</p>
            {% if sales or products%}
                <!--Sale Display-->
                    <h6>Sales</h6>
                    <hr>
                    {% for sale in sales %}
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body">
                                    <h3 class="card-title">
                                        <a href="{% url "sale_detail" sale.id %}" class="badge bg-success text-light">#{{sale.id}}</a> |
                                        <a href="{% url 'product_detail' sale.product.id %}">{{sale.product}}</a>
                                    </h3>
                                    <p class="card-text">Date Issued: <span class='badge bg-secondary'>{{sale.date_issued|date}}</span></p>
                                    <p class="card-text">Issued By: <span class="badge bg-danger">{{sale.issued_by.username}}</span></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <hr>
                <!--Product Display-->
                    <h6>Products</h6>
                    <hr>
                    <p>{{products_count}} product{{products_count|pluralize}} available</p>
                    {% for product in products %}
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body">
                                    <h3 class="card-title">
                                        <a href="{% url "product_detail" product.id %}" class="badge bg-success text-light">#{{product.id}}</a> |
                                        <a href="{% url 'product_detail' product.id %}">{{product.name}}</a>
                                    </h3>
                                    <p class="card-text">MFD. Date: <span class="badge bg-secondary">{{product.manufacturing_date|date}}</span></p>
                                    <p class="card-text">EXP. Date: <span class="badge bg-secondary">{{product.expiry_date|date}}</span></p>
                                    <p class="card-text">Created By: <span class="badge bg-danger">{{product.created_by}}</span></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            {% else %}
                <h4 class="text-center">No seach result found for "{{query}}"</h4>
            {% endif %}
            
        </div>
        
    </div>
</div>




{% endblock  %}


<div class="search-mt container">
    <div class="row">
        {% if sales %}
            {% for sale in sales %}
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="{% url "sale_detail" sale.id %}" class="badge bg-success text-light">#{{sale.id}}</a> |
                            <a href="{% url 'product_detail' sale.product.id %}">{{sale.product}}</a>
                        </h3>
                        <p class="card-text">{{sale.date_issued}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <h1>Nothing Found</h1>
        {% endif %}
        
    </div>
    
</div>

templates/store/view_product.html
{% extends "base/base.html" %}

{% block title %}View Product{% endblock  %}



{% block content %}

{% include "base/main_nav.html" %}

{% include "base/side_nav.html" %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url "dashboard" %}">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

            <div class="card">
                <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                    {% comment %} <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> {% endcomment %}
                    <small class="fw-bold">
                        Product Name: <span class="badge bg-success text-center">{{product.name|capfirst}}</span>
                    </small>
                    <small class="">
                        Product ID: <a href="{% url  "product_detail" product.id %}" class="">#{{product.id}}</a>
                    </small>
                </div>
            </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <h5 class="card-title">Description</h5>
                  <p class="small fst-italic">{{product.description|truncatewords:20}}</p>

                  <h5 class="card-title">Product Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Product Name</div>
                    <div class="col-lg-9 col-md-8"><b>{{product.name}}</b></div>
                  </div>

                  <div class="row">
                    {% if product_cat %}
                    <div class="col-lg-3 col-md-4 label">
                        {% if product_cat_count > 1 %}
                        Categories
                        {% else %}
                        Category
                        {% endif %}
                    </div>
                    
                        <div class="col-lg-9 col-md-8">
                            {% for category in product.category.all %}
                                <span class="badge bg-success">{{category.name}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Price</div>
                    <div class="col-lg-9 col-md-8">₵{{product.price}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Stock Quantity</div>
                    <div class="col-lg-9 col-md-8">
                        {% if product.quantity < 10 %}
                            <span class="badge bg-danger">{{product.quantity}} pc{{ product.quantity|pluralize }}</span>
                        {% else %}
                            <span class="badge bg-success">{{product.quantity}} pc{{ product.quantity|pluralize }}</span>
                        {% endif %}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Manufacturing Date</div>
                    <div class="col-lg-9 col-md-8">{{product.manufacturing_date|date}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Expiry Date</div>
                    <div class="col-lg-9 col-md-8">{{product.expiry_date|date}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Status</div>
                    <div class="col-lg-9 col-md-8">
                      {% if product.status == 'Active' %}
                        <span class="badge rounded-pill bg-success">{{product.status}}</span>
                      {% else %}
                        <span class="badge rounded-pill bg-danger">{{product.status|truncatechars:11}}</span>
                      {% endif %}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Created By</div>
                    <div class="col-lg-9 col-md-8">{{product.created_by}}</div>
                  </div>

                </div>

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->


{% endblock  %}